### PR TITLE
Exported json button

### PR DESCRIPTION
**Pull request by icymanred**
https://discord.com/channels/1099468797410283540/1196601985894449152

### CODE REVIEW

**Comment by bluepilledgreat** [comment]
What's the point of this if you can just copy ClientAppSettings.json? Would be more useful if it copies the flag list to clipboard.

**Comment by icymanred** [comment]
if i knew how to update pull requests id do that

**Comment by icymanred** [comment]
> What's the point of this if you can just copy ClientAppSettings.json? Would be more useful if it copies the flag list to clipboard.

Done

**Review by olliedean — CHANGES_REQUESTED** [review]
Click event is still ExportJSONButton_Click, even though that event doesn't exist anymore.
Please test your code instead of just editing it straight through github.

**Pull request closed without merging**
