### PR TITLE
Add fix for ReShade

### PR DESCRIPTION
**Pull request by DesMS**
Add a option to fix Roblox when ReShade is installed (ReShade 6.0.0+)

Regarding https://github.com/pizzaboxer/bloxstrap/issues/1237

### CODE REVIEW

**Comment by DesMS** [comment]
Might have a few bugs, but, the code seems to work fine

**Comment by bluepilledgreat** [comment]
This is an ugly hack, reminds me of #548. Please find a better way of doing this!

**Comment by DesMS** [comment]
There really is no better way to do this, it's just moving a folder (cc https://www.pcgamingwiki.com/wiki/ReShade#Vulkan ). It only asks for administrator once (That could probably be added via UI), but, here's an explanation:

```cs
if (App.Settings.Prop.ReshadeFixLaunching == true)
{
    if (Directory.Exists("C:\\ProgramData\\ReShade"))
    {
        // Next place for code
    }
}
```
This checks if the ReShade folder exists
```cs
if (Directory.Exists("C:\\ProgramData\\ReShade"))
{
// ...
    try
    {
        Directory.Move("C:\\ProgramData\\ReShade", "C:\\ProgramData\\ReShade_fix"); // Move ReShade's directory so it won't launch with NVIDIA (6.0.0+)
        App.Logger.WriteLine(LOG_IDENT, $"Moved ReShade to a position where it won't inject into Roblox."); // Log for debug
    }
    catch (Exception)
    {
        // Next place for code
    }
// ...
}
```
This checks if there's an exception (Aka, failed to move)
```cs
catch (Exception)
{
// ...
    App.Logger.WriteLine(LOG_IDENT, $"Unable to move ReShade, checking if fix is applicable");
    var acl = new FileInfo("C:\\ProgramData\\ReShade_fix").GetAccessControl(); // Check if we need to change permissions
    AuthorizationRuleCollection rules = acl.GetAccessRules(true, true, typeof(NTAccount));
    bool needs = true;
    foreach (AuthorizationRule rule in rules)
    {
        if (rule.IdentityReference.Value.Equals("Everyone", StringComparison.CurrentCultureIgnoreCase))
        {
            var filesystemAccessRule = (FileSystemAccessRule)rule;
            //Cast to a FileSystemAccessRule to check for access rights
            if (!((filesystemAccessRule.FileSystemRights & FileSystemRights.Modify) > 0 && filesystemAccessRule.AccessControlType != AccessControlType.Deny))
            {
                needs = true;
                break;
            }
            else
            {
                needs = false;
            }
        }
    }
    // Next piece of code
// ...
}
```
This piece of code checks if the directory has permissions issues. Default ReShade directory permissions:
image
We need permissions to move the folder, this checks if we need to add those
```cs
}
// ...
if (needs)
{
    try
    {
        System.Windows.Forms.MessageBox.Show("Bloxstrap needs administrator permission to fix the permissions issue with ReShade, this should only happen once.");
        App.Logger.WriteLine(LOG_IDENT, $"Attempting a permission fix"); // Log without crashing
        Process process = new Process();
        ProcessStartInfo startInfo2 = new ProcessStartInfo();
        startInfo2.WindowStyle = ProcessWindowStyle.Hidden;
        startInfo2.CreateNoWindow = true;
        startInfo2.UseShellExecute = true;
        startInfo2.FileName = "powershell.exe";
        startInfo2.Arguments = "-Command \"Start-Process icacls \\\"C:\\ProgramData\\ReShade_fix /grant Everyone:(OI)(CI)F /T\\\" -Verb RunAs\""; // Fix
        process.StartInfo = startInfo2;
        process.Start();
        process.WaitForExit(1000 * 10);
    }
    catch (Exception) { }
}
// Next piece of code
// ...
```
This code attempts to change the permissions of the folder, so that we can modify it (Launches in admin, as that's the only way to change perms)
```cs
// ...
try
{
    Directory.Move("C:\\ProgramData\\ReShade_fix", "C:\\ProgramData\\ReShade"); // Move ReShade's directory so it won't launch with NVIDIA (6.0.0+)
    App.Logger.WriteLine(LOG_IDENT, $"Moved ReShade to a position where it won't inject into Roblox."); // Log for debug
}
catch (Exception)
{
    App.Logger.WriteLine(LOG_IDENT, $"Unable to move ReShade, even without fix (Is it possible that something else is using ReShade?)"); // Log without crashing
}
// ...
```
Lastly, this piece of code attempts to move it (After a fix), if it still can't move it, it either couldn't change permissions, or it's in use

This code is run roughly the same when it closes, just that it moves `C:\ProgramData\ReShade_fix` to `C:\ProgramData\ReShade`, instead of the other way around

**Comment by bluepilledgreat** [comment]
> There really is no better way to do this
There likely is. Renaming a folder is lazy.

**Comment by DesMS** [comment]
Take a look at this thread: https://github.com/pizzaboxer/bloxstrap/issues/1237

It will automatically inject the `C:\ProgramData\ReShade\ReShadexx.dll` to the program

302058549-a3109b4f-0250-4d80-b8a2-2880ad5f7c5d

In Version 6.0.0+, ReShade doesn't have any option to disable global vulkan injection, and the only way to fix it, is to rename the folder

**Comment by bluepilledgreat** [comment]
> In Version 6.0.0+, ReShade doesn't have any option to disable global vulkan injection

Don't use vulkan then

**Comment by DesMS** [comment]
🤦

Video on why I have it for Vulkan: https://github.com/pizzaboxer/bloxstrap/assets/84988422/9fdfed34-fda6-460d-8fe1-fe53ebbc2f44

This is a *fix* for when ReShade is installed for a program that uses Vulkan, but isn't Roblox. Just saying "Don't use Vulkan then" is just ignoring the problem

**Comment by bluepilledgreat** [comment]
> 🤦
> 
> Video on why I have it for Vulkan: https://github.com/pizzaboxer/bloxstrap/assets/84988422/9fdfed34-fda6-460d-8fe1-fe53ebbc2f44
> 
> This is a _fix_ for when ReShade is installed for a program that uses Vulkan, but isn't Roblox. Just saying "Don't use Vulkan then" is just ignoring the problem

Sorry but this is a you issue. Nobody else is experiencing this so it isn't worth adding an ugly hack just for you. If you *really* need to use Vulkan, just use your custom build that has your fix.

**Comment by bluepilledgreat** [comment]
Also this is more of a problem with Reshade and not us.

**Comment by DesMS** [comment]
Anybody who installs ReShade will have this issue, just because I'm the person to report it, doesn't mean other people won't have that issue (And I wonder how many people reinstalled Windows or their graphics driver), with a video about ReShade with Beamng getting over 100k views, and a video on how to install it getting over 10k (This is just from BeamNG alone)

I don't understand why implementing a fix for something that makes Roblox stop working is a bad thing to implement, just because it has a solution of just moving a folder.

**Comment by bluepilledgreat** [comment]
> Anybody who installs ReShade will have this issue

Man I don't care stop using Vulkan or uninstall Reshade.

**Comment by DesMS** [comment]
It's a feature that would benefit Bloxstrap, it's already programmed, I don't see why it can't be added

**Comment by bluepilledgreat** [comment]
> It's a feature that would benefit Bloxstrap

Would, in my opinion, deteriorate the quality of Bloxstrap's code. The other software developers should fix it instead of us.

**Comment by pizzaboxer** [comment]
I'm not yet reviewing this because I'm certain that this should already be handled on ReShade's side. I'll wait until I can get more details on this.

**Comment by GoingCrazyDude** [comment]
If a user while playing a game happens to lose power, bsod or anything similar, the Reshade folder will remain as Reshade_fix. This will break reshade as you'd imagine. Needing to launch roblox then close it just to make sure the folder is renamed is kinda stupid. Not only that, some users might disable that option after bsod, etc. and then reshade will not work for them. Overall renaming a folder is just not a good idea tbh.

**Comment by DesMS** [comment]
Unless the registry version works, this would be the only way to fix it (And, if you were to launch Roblox, and have an unexpected incident, like those described, when you would relaunch and close Roblox, it would automatically fix). It could also have a popup when you open Roblox after a power-outage or sudden stop (Or when you activate it), I don't have much time this week to implement it, but I'm pretty sure a warning popup would provide enough info for if that were to happen.

**Comment by axellse** [comment]
As others mentioned, this problem is so specific i dont think its worth implementing a fix like this. If you want to use this and maintain it, go for it, but i dont think this needs to be added into bloxstrap.

**Comment by user1126s** [comment]
its a nice fix but you should make sure to maintain this (fix issues when happened). i will test this once i reinstall windows. (on linux rn). but you should do it on another branch or make it in a separate folder so there is no conflicts and so that the advanced users who want it can do so OR just add a link in the readme to your repo. i am new to this stuff so i might not be correct.

**Comment by pizzaboxer** [comment]
I'm going to close this because of the janky, potentially unreliable nature of it, and also because it's going to conflict heavily with my plans for redoing the whole system (#810)

**Pull request closed without merging**
