### PR TITLE
hide power tools

### PR DESCRIPTION
**Pull request by bluepilledgreat**
make them less visible

### CODE REVIEW

**Comment by GoingCrazyDude** [comment]
revolutionary

**Comment by d44df016fe28bc8d5974** [comment]
why not create a proper toggle in the bloxstrap menu

**Comment by bluepilledgreat** [comment]
> why not create a proper toggle in the bloxstrap menu

because normal users shouldnt have this on

**Comment by d44df016fe28bc8d5974** [comment]
> > why not create a proper toggle in the bloxstrap menu
> 
> because normal users shouldnt have them on

doesn't matter, i will continue advertising this feature to normal users who don't know what it does

**Review by pizzaboxer — APPROVED** [review]

**Comment by pizzaboxer** [comment]
> doesn't matter, i will continue advertising this feature to normal users who don't know what it does

what are they even going to do with them lol

**Comment by d44df016fe28bc8d5974** [comment]
> > doesn't matter, i will continue advertising this feature to normal users who don't know what it does
> 
> what are they even going to do with them lol

the channel switcher could be useful for users who want to see more of roblox
(find new stuff in other roblox builds)

**Comment by devstacking** [comment]
> > doesn't matter, i will continue advertising this feature to normal users who don't know what it does
> 
> what are they even going to do with them lol

FStringDebugShowFlagState is useful for finding default values or seeing what value you put on a flag and removing debug options makes it harder to change it

**Comment by bluepilledgreat** [comment]
> the channel switcher could be useful for users who want to see more of roblox (find new stuff in other roblox builds)

the only public channel is zflag (same as live) so gl with that

**Comment by d44df016fe28bc8d5974** [comment]
> > the channel switcher could be useful for users who want to see more of roblox (find new stuff in other roblox builds)
> 
> the only public channel is zflag (same as live) so gl with that

no matt, roblox sometimes "messes up" and makes a private channel public for a few days
so it's not useless

**Comment by d44df016fe28bc8d5974** [comment]
you can clearly see that in your channel tracker server

**Comment by bluepilledgreat** [comment]
> no matt, roblox sometimes "messes up" and makes a private channel public for a few days so it's not useless

no, they intentionally make it public so they can enroll people to the channel

**Comment by d44df016fe28bc8d5974** [comment]
still the switcher is useful for users who want to play on a different channel

**Comment by bluepilledgreat** [comment]
> still the switcher is useful for users who want to play on a different channel

then enable it. we're only hiding this stuff away from people who are inexperienced and have no idea what they are doing.

**Comment by GoingCrazyDude** [comment]
roblox players are too stupid to be able to use stuff like a channel switcher

**Comment by d44df016fe28bc8d5974** [comment]
fr tezos

**Comment by pizzaboxer** [comment]
> then enable it. we're only hiding this stuff away from people who are inexperienced and have no idea what they are doing.

^

we only hid the option away because most of the time no channels of actual interest will be usable

**Comment by pizzaboxer** [comment]
> FStringDebugShowFlagState is useful for finding default values or seeing what value you put on a flag and removing debug options makes it harder to change it

that's the only thing i agree with but in its current state it sucks to use which i've been wanting to improve

**Comment by d44df016fe28bc8d5974** [comment]
> > then enable it. we're only hiding this stuff away from people who are inexperienced and have no idea what they are doing.
> 
> ^
> 
> we only hid the option away because most of the time no channels of actual interest will be usable

as matt said sometimes roblox makes znext public to assign users to it
zbeta too

**Pull request merged**
