### PR TITLE
Remove ReShade from feature list (#190)

### PR DESCRIPTION
**Pull request by pizzaboxer**
lmao

### CODE REVIEW

**Comment by SavRekt** [comment]
Hey bro can u get new version on bloxstrap roblox patched it we didnt play without beta pls fix it fastly

**Comment by pizzaboxer** [comment]
what

**Comment by SavRekt** [comment]
> what

When the new version of bloxstrap will come?

**Comment by pizzaboxer** [comment]
what's wrong with the current one

**Comment by SavRekt** [comment]
> what's wrong with the current one

Reshade is broken

**Comment by pizzaboxer** [comment]
did you read v2.3.0's release notes or no

**Comment by SavRekt** [comment]
> did you read v2.3.0's release notes or no

yes i already readed

**Pull request merged**
