### PR TITLE
fix uninstall reg key for roblox

### PR DESCRIPTION
**Pull request by Extravi**
When you uninstall Bloxstrap, the registry key to open Roblox from the website is incorrect. This PR fixes it.
before
image
after
image

### CODE REVIEW

**Comment by bluepilledgreat** [comment]
Does this also occur with the studio case?

**Comment by Extravi** [comment]
studio? I haven't checked

**Comment by Extravi** [comment]
this pull request can be edited I'm not at my computer rn

**Comment by Extravi** [comment]
@bluepilledgreat i dont see any settings for studio i see it in the code but not bloxstrap itself?

**Comment by Extravi** [comment]
when i install bloxstrap after i compile it it does not edit the studio reg key only roblox

**Comment by Extravi** [comment]
image

**Comment by pizzaboxer** [comment]
Has it always been like that? I remember this worked when I last test it, mine just might have a had a trailing slash for some reason
In which case, this needs to use the proper Path.Combine function instead of just doing this

**Comment by Extravi** [comment]
> Has it always been like that? I remember this worked when I last tested it, mine just might have a had a trailing slash for some reason In which case, this needs to use the proper Path.Combine function instead of just doing this

https://github.com/pizzaboxer/bloxstrap/pull/1973

from my test it does not work correctly and for some bloxshade users

**Comment by NoddleLi** [comment]
idk really know

**Pull request closed without merging**
