### PR TITLE
Fluent progress dialogs

### PR DESCRIPTION
**Pull request by bluepilledgreat**
Adds fluent versions of the progress dialog. Normal fluent & aero modes included!

### CODE REVIEW

**Comment by bluepilledgreat** [comment]
Hi my name is Snapple.
My background consists of: Watermelon and Lemonade.
The more you open this door and the more you hold me my temperature goes down and I'm not drinkable no more.
# CLOSE THE GOD DAMN DOOR!

**Comment by bluepilledgreat** [comment]
Needs testing on Windows 7, 8, and 11.

**Comment by bluepilledgreat** [comment]
Only problem is that it looks HORRIBLE with light mode.

**Comment by bluepilledgreat** [comment]
Only problem is that it looks horrible with contrasting colours.

**Comment by bluepilledgreat** [comment]
Gathered feedback and improved the look of the dialog. Also fixed contrasting colours looking ugly.

**Comment by pizzaboxer** [comment]
lgtm, will need further testing on older versions of windows

**Pull request merged**
