### PR TITLE
Create roblox

### PR DESCRIPTION
**Pull request by usernamedboncdabuider**

### CODE REVIEW

**Comment by bluepilledgreat** [comment]
@pizzaboxer re-open this

**Comment by Delzo** [comment]
create it

**Comment by OrphanObliterator** [comment]
> create it

dont

**Comment by axellse** [comment]
Very useful feature

**Comment by RealFunkyWorm** [comment]
create it NOW

**Comment by GoingCrazyDude** [comment]
re open this NOW!

**Comment by Devraj2010isme** [comment]
now that pizzaboxer is no longer in charge,.. can this be reopened?

**Comment by funkywormi** [comment]
Probably 🤔

**Pull request closed without merging**
