### PR TITLE
Join last server

### PR DESCRIPTION
**Pull request by atomsk-0**
Implements join last server option to tray icon #887

### CODE REVIEW

**Comment by VoidNmbrZero** [comment]
I hope this one gets merged

**Comment by VoidNmbrZero** [comment]
> Would be cool to connect the last server, if you closed roblox, and then opened it again (if it's possible ofc)

Im pretty sure you can just save the info gathered from previous server in a file, removing itself on system restart.

**Comment by mynameisseif** [comment]
maybe add server history too ? arranged from the oldest to the latest

**Comment by pizzaboxer** [comment]
Working on it myself.

I didn't even see @mynameisseif's suggestion before working on this, honestly, but that's literally what I did.


https://github.com/user-attachments/assets/0a8dc872-50d2-4124-9ab7-83a248fde319

**Pull request closed without merging**
