### PR TITLE
Add Presets

### LINKED ISSUE #610: Feature Request - Flag to enable this new feature (in-experience controls new look)
Bloxy_News have tweeted the following new in-experience controls look and i was wondering if there's a flag for this and if so, could be added to the next update for Bloxstrap?
image

### PR DESCRIPTION
**Pull request by Cristiano100**
Closes #610

### CODE REVIEW

**Review by bluepilledgreat — APPROVED** [review]

**Comment by Cristiano100** [comment]
Changed title because there's 2 additional flag presets.

**Comment by pizzaboxer** [comment]
I'll look at this later once I have enough time

**Review by EasternBloxxer — APPROVED** [review]

**Review by WaviestBalloon — APPROVED** [review]
łŋŧµ¹

**Comment by user1126s** [comment]
hey, so what are the fflags you added, i want to enable them. also, @pizzaboxer  when this gunna get merged?

**Comment by Cristiano100** [comment]
@user1126s this is closed

**Pull request closed without merging**
