### PR TITLE
Add replacing channel name for download + slight RobloxDeployment cleanup

### PR DESCRIPTION
**Pull request by bluepilledgreat**
Fixes downloading channels that have `FFlagReplaceChannelNameForDownload` on.
Tested:
- LIVE (flag off)
- ZFlag (flag on)
- ZSplitHashUpdateTesting (flag off)

### CODE REVIEW

**Comment by pizzaboxer** [comment]
i just know backporting all of this into the 2.5.4 code is going tom ake me kill myself

**Comment by d44df016fe28bc8d5974** [comment]
> i just know backporting all of this into the 2.5.4 code is going tom ake me kill myself

so when will this happen
or is it removed forever

**Comment by bluepilledgreat** [comment]
> > i just know backporting all of this into the 2.5.4 code is going tom ake me kill myself
> 
> so when will this happen or is it removed forever

It is not happening. 2.5.5 was scrapped in favour of releasing 2.6.0.

**Comment by d44df016fe28bc8d5974** [comment]
> > > i just know backporting all of this into the 2.5.4 code is going tom ake me kill myself
> > 
> > 
> > so when will this happen or is it removed forever
> 
> It is not happening. 2.5.5 was scrapped in favour of releasing 2.6.0.

what about in 2.6.0+ 
again behind a hidden setting there are real use cases for it

**Comment by d44df016fe28bc8d5974** [comment]
what about 2.7.0+ and above

**Pull request merged**
