### PR TITLE
add warning to readme

### PR DESCRIPTION
**Pull request by bluepilledgreat**
amazing idea stolen from @7ap

### CODE REVIEW

**Review by axellse — APPROVED** [review]

**Comment by GoingCrazyDude** [comment]
lgtm

**Comment by Vlad55432** [comment]
LMAO

**Comment by d44df016fe28bc8d5974** [comment]
amazing

**Comment by pizzaboxer** [comment]
lmao

**Comment by Tarvey** [comment]
yeah

**Pull request closed without merging**
